# Generated by Django 6.0.2 on 2026-02-16 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        ('casos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='caso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casos.caso'),
        ),
    ]
