# Generated by Django 6.0.2 on 2026-02-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_caso', models.CharField(max_length=50)),
                ('nro_expediente', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('dias', models.IntegerField()),
                ('mes', models.CharField(max_length=20)),
                ('movil_afectado', models.CharField(max_length=100)),
                ('tipo_caso', models.CharField(max_length=100)),
                ('tipo_irregularidad', models.CharField(max_length=100)),
                ('subtipo_irregularidad', models.CharField(max_length=100)),
                ('objetivo_agraviado', models.CharField(max_length=200)),
                ('incidencia', models.TextField()),
                ('duracion_dias', models.IntegerField()),
                ('descripcion_modus_operandi', models.TextField()),
                ('area_apoyo', models.CharField(max_length=200)),
                ('deteccion_procedencia', models.TextField()),
                ('diagnostico', models.TextField()),
                ('actuaciones', models.TextField()),
                ('conclusiones', models.TextField()),
                ('observaciones', models.TextField()),
                ('soporte', models.FileField(blank=True, null=True, upload_to='soportes/')),
                ('estatus', models.CharField(choices=[('ABIERTO', 'Abierto'), ('ASIGNADO', 'Asignado'), ('CERRADO', 'Cerrado')], max_length=20)),
            ],
        ),
    ]
