# Generated by Django 6.0.2 on 2026-02-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='tipo_caso',
            field=models.CharField(choices=[('GESTION', 'Gestión'), ('RECLAMO', 'Reclamo'), ('CASO', 'Caso')], max_length=20),
        ),
    ]
